version: '3.8'

services:
  mightsea-postgres:
    image: postgres:14.3-alpine3.15
    container_name: mightsea-postgres
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./configs/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6.9
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: me@lzok.me
      PGADMIN_DEFAULT_PASSWORD: asdasdasd
    volumes:
      # Be sure that the host folder has the right permissions
      # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#mapped-files-and-directories
      # FYI: sudo chown -R 5050:5050 ./volumes/pgadmin
      - ./volumes/pgadmin:/var/lib/pgadmin

  storage-1:
    image: minio/minio:RELEASE.2022-04-26T01-20-24Z
    container_name: mightsea-object-storage
    volumes:
      - ./volumes/object-storage:/data1
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    command: server --address :9000 --console-address :9001 /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    depends_on:
      mightsea-postgres:
        condition: service_healthy

  mc:
    image: minio/mc:RELEASE.2021-04-22T17-40-00Z
    container_name: minio-mc-command
    restart: on-failure
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    volumes:
      - ./configs/minio/setup.sh:/minio-setup.sh
    entrypoint: /minio-setup.sh
    depends_on:
      - storage-1

  nginx:
    image: nginx:1.20.0-alpine
    container_name: mightsea-nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/common-headers.conf:/etc/nginx/common-headers.conf:ro
      - ./configs/nginx/sites-available:/etc/nginx/sites-available:ro
      - ./configs/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
      target: dev
    container_name: mightsea-backend
    command: npm run dev
    env_file:
      - ../server/.env
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: development
    volumes:
      - '../server:/opt/app'
      - node-modules-back:/opt/app/node_modules
    depends_on:
      mightsea-postgres:
        condition: service_healthy

  # frontend:
  #   build:
  #     context: ../client
  #     dockerfile: Dockerfile
  #     target: dev
  #   container_name: mightsea-frontend
  #   command: npm run dev
  #   env_file:
  #     - ../client/.env.local
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - '../client:/opt/app'
  #     - '../library:/opt/library'
  #     - '../utils:/opt/utils'
  #     - node-modules-front:/opt/app/node_modules
  #   depends_on:
  #     - backend

volumes:
  # node-modules-front:
  node-modules-back: